name: Test Theme

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-theme:
    name: Test theme on node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - "12"
          - "14"
          - "16"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Build project
        run: pnpm run build

      - name: Linter test
        run: |
          pnpm run lint:check
          pnpm run lint:md

      - name: Unit test
        run: pnpm run test

      - name: Upload coverage
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm 6
        if: matrix.node == '12'
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Test Demo Build
        run: |
          pnpm run demo:build
